spring:
  config:
    activate:
      on-profile: local

  datasource:
    writer:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/onlog_blog?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
      username: root
      password: 12345

    reader:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/onlog_blog
      username: root
      password: 12345

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace